Class_rule =[
    {
      'brand':[
                ['karihome'],
                ['karih'],
                ['karthome'],
                ['thome'],
                ['2-ranihome'],
                ['krarihome'],
                ['glucerna'],
                ['glucenh'],
                ['glucema'],
                ['gluceraaa'],
              ],
      'text':
      [
          {
              'class':'Karihome_Goat_3',
              'rule':[
                      ['3'],
                      ['growing-up']
              ]
          },
          {
              'class':'Karihome_Goat_4',
              'rule':[
                      ['4']
              ]
          },
          {
              'class':'Karihome_Goat_2',
              'rule':[
                      ['2'],
                      ['follow-on'],
                      ['follow-onfo'],
              ]
          },
          {
              'class':'Karihome_Goat_1',
              'rule':[
                      ['1']
              ]
          },
          {
              'class':'Abbout_Glucerna',
              'rule':[
                      ['glucerna'],
                      ['glucema'],
                      ['glucenh '],
                      ['glucen'],
                      ['gluceraaa'],
                      ['gluceraaa'],
              ]
          },
          {
              'class':'Karihome_Goat_Whole_Powder',
              'rule':[
                      ['whole'],
              ]
          },
          {
              'class':'Karihome_Cow_2-FL',
              'rule':[
                      ['2-fl'],
                      ['cow']
              ]
          },
          {
              'class':'Karihome_Assorted',
              'rule':[
                      ['assorted'],
                      ['assurteo'],
                      ['assanted'],
                      ['asscod'],
              ]
          },
          {
                'class':'Karihome_Chocolate',
                'rule':[
                        ['chocolate'],
                ]
          },
          {
              'class':'Karihome_Yogurt',
              'rule':[
                      ['yogurt'],
              ]
          },
          {
              'class':'Karihome_Strawberry',
              'rule':[
                      ['strawberry'],
                      ['grawberry'],
              ]
          },
          {
              'class':'Karihome_Blueberry',
              'rule':[
                      ['blueberry'],
                      ['slueberry'],
              ]
          },
      ]  
    },
    {
        'brand':[
                ['nestle'],
              ],
      'text':
      [
        {
            'class':'Nestle_MOM',
            'rule':[
                    ['mom'],
                    ['mộm'],
                    ['môm'],
                    ['mọm']
            ]
        },
        
      ]
    },
    {
        'brand':[
                ['lactogen'],
                ['lactogrow'],
                ['nido'],
              ],
      'text':
      [
        {
            'class':'Nestle_Lactogrow_1_3',
            'rule':[
                    ['lactogrow','1-3'],
                    ['lactogrow','1~3'],
            ]
        },
        {
            'class':'Nestle_Lactogrow_3',
            'rule':[
                    ['lactogrow','3'],
            ]
        },
        {
            'class':'Nestle_Lactogrow_4',
            'rule':[
                    ['lactogrow','4'],
            ]
        },
        {
            'class':'Nestle_Lactogen_1',
            'rule':[
                    ['lactogen','1'],
            ]
        },
        {
            'class':'Nestle_Lactogen_2',
            'rule':[
                    ['lactogen','2'],
            ]
        },
        {
            'class':'Nestle_Lactogen_3',
            'rule':[
                    ['lactogen','3'],
            ]
        },
        {
              'class':'Nestle_Nido_Kinder_1',
              'rule':[
                      ['nido','kinder'],
                      ['nido','1+'],
                      ['kinder','1+'],
              ]
        },
      ]
    },
    
    {
        'brand':[
                ['soothepro'],
                ['good'],
                ['gosd'],
                ['start'],
                ['gerber'],
              ],
      'text':
      [
        {
                'class':'GERBER_Good_Start_SoothePro',
                'rule':[
                        ['soothepro'],
                ]
          },
          {
                'class':'GERBER_Good_Start_SoothePro_1',
                'rule':[
                        ['soothepro','1'],
                ]
          },
          {
                'class':'GERBER_Good_Start_infant',
                'rule':[
                        ['infant'],
                        ['start','infant'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Soothe',
                'rule':[
                        ['soothe'],
                        ['vitamin','probiotic'],
                ]
          },
          {
                'class':'GERBER_Good_Start_a2_advanced',
                'rule':[
                        ['good','a2','start'],
                ]
          },
          {
                'class':'GERBER_Good_Start_a2_advanced',
                'rule':[
                        ['good','a2','advanced'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Grow_Toddler_Probiotic_1',
                'rule':[
                        ['digestive','1+'],
                        ['1+','probiotic'],
                        ['1+','support']
                ]
          },
          {
                'class':'GERBER_Good_Start_Grow_Toddler_Probiotic_3',
                'rule':[
                        ['digestive','3+'],
                        ['3+','probiotic'],
                        ['3+','support']
                ]
          },
         {
                'class':'GERBER_Good_Start_Probiotics',
                'rule':[
                        ['probiotics','good'],
                        ['everyday','good'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Gentle_Supreme_1',
                'rule':[
                        ['gentle','supreme','1'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Gentle_Supreme_2',
                'rule':[
                        ['supreme','2'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Gentle_Supreme_3',
                'rule':[
                        ['gentle','3'],
                ]
          },
      ]
    },
    {
        'brand':[
                ['gerber'],
                ['gorber'],
                ['gentlepro'],
              ],
      'text':
      [
          {
                'class':'GERBER_Organic_Teether',
                'rule':[
                        ['organic,teether'],
                        ['organic,blueberry'],
                ]
          },
          {
                'class':'GERBER_Organic_oatmeal',
                'rule':[
                        ['organic,oatmeal'],
                        ['organic,rice'],
                ]
          },
          {
                'class':'GERBER_Hearty_MultiGrain',
                'rule':[
                        ['multigrain'],
                ]
          },
          {
                'class':'GERBER_Whole_Wheat',
                'rule':[
                        ['whole,wheat'],
                ]
          },
          {
                'class':'GERBER_Rice',
                'rule':[
                        ['rice'],
                ]
          },
          {
                'class':'GERBER_Yogurt_Melts',
                'rule':[
                        ['yogurt','melts'],
                ]
          },
          {
                'class':'GERBER_Arrowroot_Biscuits',
                'rule':[
                        ['arrowroot','biscuits'],
                ]
          },
          {
                'class':'GERBER_Organic_Puffs',
                'rule':[
                        ['organic','puffs'],
                ]
          },
          {
                'class':'GERBER_Puffs',
                'rule':[
                        ['puffs'],
                        ['graduates','puffs']
                ]
          },
          {
                'class':'GERBER_Apple_Juice',
                'rule':[
                        ['apple'],
                        ['pear'],
                ]
          },
          {
                'class':'GERBER_Good_Start_GentlePro',
                'rule':[
                        ['gentlepro'],
                ]
          },
          {
                'class':'GERBER_Good_Start_GentlePro_1',
                'rule':[
                        ['gentlepro','1'],
                ]
          },
          {
                'class':'GERBER_Good_Start_GentlePro_2',
                'rule':[
                        ['gentlepro','2'],

                ]
          },
          {
                'class':'GERBER_Good_Start_GentlePro_3',
                'rule':[
                        ['gentlepro','3'],

                ]
          },
          {
                'class':'GERBER_Good_Start_Gentle_1',
                'rule':[
                        ['gentle','1'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Gentle_Supreme_1',
                'rule':[
                        ['gentle','supreme','1'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Gentle_Supreme_3',
                'rule':[
                        ['gentle','supreme','3'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Extensive_HA',
                'rule':[
                        ['extensive','ha'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Soy_1',
                'rule':[
                        ['gentle','soy','1'],
                ]
          },
          {
                'class':'GERBER_Good_Start_Soy_2',
                'rule':[
                        ['gentle','soy','2'],
                ]
          },
          {
                'class':'GERBER_Extensive_HA',
                'rule':[
                        ['extensive','ha'],
                ]
          },
      ]
    },
    {
        'brand':[
                ['nan'],
                ['năn'],
                ['nanha'],
                ['nankid'],
              ],
      'text':
      [
        
        {
            'class':'Nestle_Pre_NAN',
            'rule':[
                    ['pre'],
            ]
        },  
          {
                'class':'NAN_SUPREMEpro_1',
                'rule':[
                        ['supremepro','1'],

                ]
          },
          {
                'class':'NAN_SUPREMEpro_2',
                'rule':[
                        ['supremepro','2'],

                ]
          },
          {
                'class':'NAN_SUPREMEpro_3',
                'rule':[
                        ['supremepro','3'],

                ]
          },
          {
                'class':'NAN_COMFORT_1',
                'rule':[
                        ['comfort','1'],

                ]
          },
          {
                'class':'NAN_COMFORT_2',
                'rule':[
                        ['comfort','2'],

                ]
          },
          {
                'class':'NAN_COMFORT_3',
                'rule':[
                        ['comfort','3'],

                ]
          },
          {
                'class':'NAN_A2_1',
                'rule':[
                        ['1','a2'],
                ]
          },
          {
                'class':'NAN_A2_2',
                'rule':[
                        ['2','a2'],
                ]
          },
          {
                'class':'NAN_A2_3',
                'rule':[
                        ['a2','3'],
                ]
          },
          {
                'class':'NAN_2',
                'rule':[
                        ['2'],
                ]
          },
          {
                'class':'NAN_Gro_1',
                'rule':[
                        ['gro','1'],
                ]
          },
          {
                'class':'NAN_Kid_1',
                'rule':[
                        ['kid','1'],
                ]
          },
          {
                'class':'NAN_Gro_2',
                'rule':[
                        ['gro','2'],
                ]
          },
          {
                'class':'NAN_Kid_2',
                'rule':[
                        ['kid','2'],
                ]
          },
          {
                'class':'NAN_Gro_3',
                'rule':[
                        ['gro','3'],
                ]
          },
          {
                'class':'NAN_Kid_3',
                'rule':[
                        ['kid','3'],
                ]
          },
          {
                'class':'NAN_Gro_4',
                'rule':[
                        ['gro','4'],
                ]
          },
          {
                'class':'NAN_Kid_4',
                'rule':[
                        ['kid','4'],
                ]
          },
          {
                'class':'NAN_2',
                'rule':[
                        ['2'],
                ]
          },
          {
                'class':'NAN A.R.',
                'rule':[
                        ['a.r'],
                        ['a-r'],
                ]
          },
          {
                'class':'NAN_EXPERTpro_SENSIpro',
                'rule':[
                        ['expertpro'],
                ]
          },
          {
                'class':'NAN_LI',
                'rule':[
                        ['li'],
                        ['l.i'],
                        ['l.i.'],
                        ['l-i'],
                ]
          },
          {
                'class':'NAN_Pro_Toddler_Drink',
                'rule':[
                        ['toddler'],
                ]
          },
          {
                'class':'NAN_Pro',
                'rule':[
                        ['pro'],
                ]
          },
          {
                'class':'NAN_2',
                'rule':[
                        ['2'],
                ]
          },
          {
                'class':'NAN_1',
                'rule':[
                        ['1'],
                ]
          },
          {
                'class':'NAN_3',
                'rule':[
                        ['3'],
                ]
          },
          {
                'class':'NAN_4',
                'rule':[
                        ['4'],
                ]
          }
      ]
    },
    {
        'brand':[
                ['optipro'],
              ],
      'text':
      [
        {
        'class':'NAN_Optipro_HA_1',
        'rule':[
                ['1','ha','optipro'],
        ]
        },
        {
        'class':'NAN_Optipro_HA_2',
        'rule':[
                ['2','ha','optipro'],
        ]
        },
        {
        'class':'NAN_Optipro_HA_3',
        'rule':[
                ['3','ha','optipro'],
        ]
        },
        {
        'class':'NAN_Optipro_1',
        'rule':[
                ['optipro','1'],
        ]
        },
        {
        'class':'NAN_Optipro_2',
        'rule':[
                ['optipro','2'],
        ]
        },
        {
        'class':'NAN_Optipro_3',
        'rule':[
                ['optipro','3'],
        ]
        },
        {
        'class':'NAN_Optipro_4',
        'rule':[
                ['optipro','4'],
        ]
        },
      ]
    },
    {
        'brand':[
                ['cerelac'],
                ['cerelala'],
                ['cerel'],
              ],
      'text':
      [
        {
                'class':'Nestle_Cereals_6',
                'rule':[
                        ['6'],
                ]
          },
        {
                'class':'Nestle_Cereals_8',
                'rule':[
                        ['8'],
                ]
          },
        {
                'class':'Nestle_Cereals_7',
                'rule':[
                        ['7'],
                ]
          },
          {
              'class':'Nestle_Cereals_12',
              'rule':[
                      ['12'],
              ]
          },
        ]
    },
    {
        'brand':[
                ['lactokid'],
              ],
      'text':
      [
        {
                'class':'Lactokid_1_3',
                'rule':[
                        ['1-3'],
                        ['1~3'],
                ]
        },
        {
                'class':'Lactokid_3',
                'rule':[
                        ['3'],
                ]
        },
        {
                'class':'Lactokid_4_6',
                'rule':[
                        ['4-6'],
                        ['4~6'],
                ]
        },
        ]
    },
    {
        'brand':[
                ['frisomum'],
                ['friso'],
                ['frisolac'],
              ],
      'text':
      [
        {
            'class':'FRISOmum_Gold',
                'rule':[
                        ['frisomum','gold'],
                ]
        },
        {
            'class':'FRISO_Gold_Milk_Cereal',
                'rule':[
                        ['friso','cereal'],
                ]
        },
        {
            'class':'FRISO_Gold_3',
                'rule':[
                        ['friso','gold','3'],
                ]
        },
        {
            'class':'FRISO_Gold_4',
                'rule':[
                        ['friso','gold','4'],
                ]
        },
        {
            'class':'FRISO_Gold_1',
                'rule':[
                        ['friso','gold','1'],
                ]
        },
        {
            'class':'FRISO_Gold_2',
                'rule':[
                        ['friso','gold','2'],
                ]
        },
        {
            'class':'FRISOlac_Gold_3',
                'rule':[
                        ['frisolac','gold','3'],
                ]
        },
        {
            'class':'FRISOlac_Gold_4',
                'rule':[
                        ['frisolac','gold','4'],
                ]
        },
        {
            'class':'FRISOlac_Gold_1',
                'rule':[
                        ['frisolac','gold','1'],
                ]
        },
        {
            'class':'FRISOlac_Gold_2',
                'rule':[
                        ['frisolac','gold','2'],
                ]
        },
        {
            'class':'FRISO_1',
                'rule':[
                        ['friso','1'],
                ]
        },
        {
            'class':'FRISO_2',
                'rule':[
                        ['friso','2'],
                ]
        },
        {
            'class':'FRISO_3',
                'rule':[
                        ['friso','3'],
                ]
        },
        {
            'class':'FRISO_4',
                'rule':[
                        ['friso','4'],
                ]
        },
        
      ]
    },
    {
        'brand':[
                ['aptamil'],
                ['aptakid'],
              ],
      'text':
      [
       {
            'class':'Aptamil_Platinum_Edition_1',
                'rule':[
                        ['pro','utura','1'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_1',
                'rule':[
                        ['pro','utura','1'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_2',
                'rule':[
                        ['pro','utura','2'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_2',
                'rule':[
                        ['profutura','2'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_3',
                'rule':[
                        ['profutura','3'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_3',
                'rule':[
                        ['pro','utura','3'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_4',
                'rule':[
                        ['pro','utura','4'],
                ]
        },
        {
            'class':'Aptamil_Platinum_Edition_4',
                'rule':[
                        ['profutura','4'],
                ]
        },
        {
            'class':'Aptamil_First_Infant_1',
                'rule':[
                        ['1','infant'],
                ]
        },
        {
            'class':'Aptamil_First_Infant_1',
                'rule':[
                        ['1','first'],
                ]
        },
        {
            'class':'Aptamil_Follow_On_2',
                'rule':[
                        ['2','on'],
                ]
        },
        {
            'class':'Aptamil_Follow_On_2',
                'rule':[
                        ['2','follow'],
                ]
        },
        {
            'class':'Aptamil_Pronutra_Follow_On_2',
                'rule':[
                        ['pronutra','2','follow'],
                ]
        },
        {
            'class':'Aptamil_Follow_On_2',
                'rule':[
                        ['6-12'],
                ]
        },
        {
            'class':'Aptamil_Growing_Up_3',
                'rule':[
                        ['3','up'],
                ]
        },
        {
            'class':'Aptamil_Growing_Up_3',
                'rule':[
                        ['3','growing'],
                ]
        },
        {
            'class':'Aptamil_Growing_Up_3',
                'rule':[
                        ['growing','up'],
                ]
        },
        {
            'class':'Aptamil_Growing_Up_3',
                'rule':[
                        ['1-2'],
                ]
        },
        {
            'class':'Aptamil_Growing_Up_4',
                'rule':[
                        ['4','up'],
                ]
        },
        {
            'class':'Aptamil_Growing_Up_4',
                'rule':[
                        ['4','growing'],
                ]
        },
        {
            'class':'Aptamil_Organic_Baby_Rice',
                'rule':[
                        ['organic','baby'],
                ]
        },
        {
            'class':'Aptamil_gold_1',
                'rule':[
                        ['gold+','1'],
                ]
        },
        {
            'class':'Aptamil_gold_2',
                'rule':[
                        ['gold+','2'],
                ]
        },
        {
            'class':'Aptamil_gold_3',
                'rule':[
                        ['gold+','3'],
                ]
        },
        {
            'class':'Aptamil_gold_4',
                'rule':[
                        ['gold+','4'],
                ]
        },
        {
            'class':'Aptamil_1',
                'rule':[
                        ['1'],
                ]
        },
        {
            'class':'Aptamil_From_birth',
                'rule':[
                        ['from','birth'],
                ]
        },
        {
            'class':'Aptamil_2',
                'rule':[
                        ['2'],
                ]
        },
        {
            'class':'Aptamil_3',
                'rule':[
                        ['3'],
                ]
        },
        {
            'class':'Aptamil_4',
                'rule':[
                        ['4'],
                ]
        },
        {
            'class':'Aptamil_Cereal_4_6',
                'rule':[
                        ['4-6'],
                ]
        },
        {
            'class':'Aptamil_Cereal_7',
                'rule':[
                        ['7'],
                ]
        },
        {
            'class':'Aptamil_Cereal_10',
                'rule':[
                        ['10'],
                ]
        },
        {
            'class':'Aptamil_Cereal_10',
                'rule':[
                        ['10'],
                ]
        },


      ]
    },
    {
        'brand':[
                ['puraminojr'],
                ['puramino'],
                ['prramino'],
                # ['puramin'],
              ],
      'text':
      [
    
          {
              'class':'Puramino',
                  'rule':[
                        ['puraminojr'],
                        ['puramino'],
                        ['prramino'],
                        # ['puramin'],
                  ]
          },
      ]
    },
    {
        'brand':[
                ['enfamil'],
                ['famil'],
                ['enfam'],
                ['enfamila'],
                ['famila'],
                ['enfamila+'],
              ],
      'text':
      [
          {
              'class':'Enfamil_DHA_IN_SOY',
                  'rule':[
                          ['dha-in-soy'],
                          ['dha&ara'],
                          ['dha.in.soy'],
                  ]
          },
          {
              'class':'Enfamil_D_V_SOL',
                  'rule':[
                          ['d-v-sol'],
                          ['d.v.sol'],
                  ]
          },
          {
              'class':'Enfamil_FER_IN_SOL',
                  'rule':[
                          ['fer-in-sol'],
                          ['fer.in.sol'],
                  ]
          },
          {
              'class':'Enfamil_POLY_VI_SOL',
                  'rule':[
                          ['poly-vi-sol'],
                          ['poly.vi.sol'],
                  ]
          },
          {
              'class':'Enfamil_TRI_VI_SOL',
                  'rule':[
                          ['tri-vi-sol'],
                          ['tri.vi.sol'],
                  ]
          },
          {
              'class':'Enfamil_2',
                  'rule':[
                          ['2','1'],
                          ['follow-on','1'],
                  ]
          },
          {
              'class':'Enfamil_2',
                  'rule':[
                          ['2'],
                          ['follow-on'],
                  ]
          },
          {
              'class':'Enfamil_2',
                  'rule':[
                          ['follow-on','360'],
                          ['follow-on','a'],
                          ['follow','a'],
                  ]
          },
          {
              'class':'Enfamil_Neuro_Pro',
                  'rule':[
                          ['neuro'],
                          ['nuuro'],
                  ]
          },
          {
              'class':'Enfamil_Neuro_Pro',
                  'rule':[
                          ['neuro','1'],
                          ['neuro','gro'],
                  ]
          },
          {
              'class':'Enfamil_Neuro_Pro',
                  'rule':[
                          ['neuro','1','gro'],
                  ]
          },
          {
              'class':'Enfamil_3',
                  'rule':[
                          ['3','1'],
                  ]
          },
          {
              'class':'Enfamil_3',
                  'rule':[
                          ['3'],
                          ['growing'],
                          ['1-3'],
                  ]
          },
          {
              'class':'Enfamil_1',
                  'rule':[
                          ['1'],
                          ['7'],
                  ]
          },
          {
              'class':'Enfamil_4',
                  'rule':[
                          ['4'],
                          ['3-6'],
                  ]
          },
          {
              'class':'Enfamil_4',
                  'rule':[
                          ['4','1'],
                  ]
          },
          {
              'class':'Enfamil_5',
                  'rule':[
                          ['5'],
                  ]
          },
          {
              'class':'Enfamil_5',
                  'rule':[
                          ['5','1'],
                  ]
          },
          {
              'class':'Enfamil_AR',
                  'rule':[
                          ['1','a.r'],
                          ['0-12','a.r'],
                          ['a.r'],
                          ['a.r.'],
                  ]
          },
          {
              'class':'Enfamil_infant',
                  'rule':[
                          ['infant'],
                  ]
          },
          {
              'class':'Enfamil_Simply_infant',
                  'rule':[
                          ['simply','0-12'],
                  ]
          },
          {
              'class':'Enfamil_Simply_infant',
                  'rule':[
                          ['simply','infant'],
                  ]
          },
          {
              'class':'Enfamil_infant',
                  'rule':[
                          ['infant','1'],
                          ['infant','0-12'],
                          ['neuro','0-12'],
                  ]
          },
          {
              'class':'Enfamil_Gentlease',
                  'rule':[
                          ['gentlease'],
                  ]
          },
          {
              'class':'Enfamil_Gentlease',
                  'rule':[
                          ['1','gentlease'],
                  ]
          },
          {
              'class':'Enfamil_Probiotics',
                  'rule':[
                          ['probiotics'],
                  ]
          },
          {
              'class':'Enfamil_Premature',
                  'rule':[
                          ['24'],
                          ['30'],
                          ['premature'],
                  ]
          },
          {
              'class':'Enfamil_EnfaCare',
                  'rule':[
                          ['enfacare'],
                  ]
          },
          {
              'class':'Enfamom_Prenatal',
                  'rule':[
                          ['prenatal'],
                  ]
          },
          {
              'class':'Enfamom_Prenatal',
                  'rule':[
                          ['folate'],
                  ]
          },
      
      ]
    },
    {
        'brand':[
                ['nutramigen']
              ],
      'text':
      [
         
          {
              'class':'Nutramigen_LGG',
                  'rule':[
                          ['nutramigen','hypoallergenic'],
                  ]
          },
          {
              'class':'Nutramigen_LGG',
                  'rule':[
                          ['nutramigen','toddler'],
                          ['nutramigen','infant'],
                  ]
          },
      ]
    },
    {
        'brand':[
                ['enfamama'],
                ['enfamina'],
                ['entamina'],
              ],
      'text':
      [
        {
          'class':'Enfamama',
              'rule':[
                        ['enfamina'],
                        ['entamina'],
                        ['enfamama'],
              ]
        },
      ]
    },
    {
        'brand':[
                ['pregestimil'],
              ],
      'text':
      [
        {
          'class':'Pregestimil',
              'rule':[
                        ['pregestimil'],
              ]
        },
      ]
    },
    {
        'brand':[
                ['enfagrow'],
                ['enfagrowa'],
                ['enfagrowa+'],
                ['enfag'],
                ['agrow'],
                ['agrowa'],
              ],
      'text':
      [
        
          {
              'class':'Enfagrow_2',
                  'rule':[
                          ['follow-on'],
                          ['2'],
                  ]
          },
          {
              'class':'Enfagrow_pro_1',
                  'rule':[
                          ['pro','1'],
                  ]
          },
          {
              'class':'Enfagrow_pro_2',
                  'rule':[
                          ['pro','2'],
                  ]
          },
          {
              'class':'Enfagrow_pro_3',
                  'rule':[
                          ['pro','3'],
                  ]
          },
          {
              'class':'Enfagrow_2',
                  'rule':[
                          ['follow-on','a'],
                  ]
          },
          {
              'class':'Enfagrow_2',
                  'rule':[
                          ['follow-on','360'],
                  ]
          },
          {
              'class':'Enfagrow_2',
                  'rule':[
                          ['2','1'],
                  ]
          },
          {
              'class':'Enfagrow_3',
                  'rule':[
                          ['3'],
                          ['1-3'],
                  ]
          },
          {
              'class':'Enfagrow_3',
                  'rule':[
                          ['3','1'],
                  ]
          },
          {
              'class':'Enfagrow_4',
                  'rule':[
                          ['4'],
                          ['3-6'],
                  ]
          },
          {
              'class':'Enfagrow_4',
                  'rule':[
                          ['4','1'],
                  ]
          },
          {
              'class':'Enfagrow_5',
                  'rule':[
                          ['5'],
                  ]
          },
          {
              'class':'Enfagrow_5',
                  'rule':[
                          ['5','1'],
                  ]
          },
          {
              'class':'Enfagrow_1',
                  'rule':[
                          ['1'],
                  ]
          },
          {
              'class':'Enfagrow_Mindpro_a2',
                  'rule':[
                          ['mindpro','a2'],
                          ['mindpro','1-3'],
                  ]
          },
          {
              'class':'Enfagrow_Mindpro_Gentlease',
                  'rule':[
                          ['mindpro','gentlease'],
                  ]
          },
          {
              'class':'Enfagrow_Mindpro',
                  'rule':[
                          ['mindpro'],
                  ]
          },
          {
              'class':'Enfagrow_Toddler_Transitions_Gentlease',
                  'rule':[
                          ['transitions','gentlease','toddler'],
                  ]
          },
          {
              'class':'Enfagrow_Gentlease_Toddler',
                  'rule':[
                          ['gentlease','toddler'],
                  ]
          },
         {
              'class':'Enfagrow_Gentlease',
                  'rule':[
                          ['gentlease'],
                  ]
          },
         {
              'class':'Enfagrow_Gentlease_1',
                  'rule':[
                          ['gentlease','1'],
                  ]
          },
         {
              'class':'Enfagrow_Gentlease_2',
                  'rule':[
                          ['gentlease','2'],
                  ]
          },
         {
              'class':'Enfagrow_Gentlease_3',
                  'rule':[
                          ['gentlease','3'],
                  ]
          },
          {
              'class':'Enfagrow_Toddler_Transitions',
                  'rule':[
                          ['transitions','toddler'],
                  ]
          },
          {
              'class':'Enfagrow_Toddler_Next_Step',
                  'rule':[
                          ['next','toddler'],
                          ['step','toddler'],
                          ['next','step'],
                  ]
          },
          {
              'class':'Enfagrow_Toddler',
                  'rule':[
                          ['toddler'],
                          ['nutritional','drink'],
                  ]
          },
      ]
    },

    {
        'brand':[
                ['enspire'],
                ['(nspire'],
              ],
      'text':
      [
        
          {
              'class':'Enfagrow_Enspire_Toddler',
                  'rule':[
                          ['enspire','toddler'],
                          ['(nspire','toddler'],
                  ]
          },
          {
              'class':'Enfamil_Enspire',
                  'rule':[
                          ['enspire'],
                          ['(nspire'],
                  ]
          },
          {
              'class':'Enfamil_Enspire',
                  'rule':[
                          ['enspire','gentlease','infant'],
                  ]
          },
          {
              'class':'Enfamil_Enspire',
                  'rule':[
                          ['enfamil','enspire','infant'],
                  ]
          },
      ]
    },
    {
        'brand':[
                ['gain'],
              ],
      'text':
      [         {        
              'class':'Similac_3',
                  'rule':[
                          ['plus','3'],
                  ]
          },
      ]
    },
    {
        'brand':[
                ['bliss'],
              ],
      'text':
      [
        {
                'class':'Similac_Pure_Bliss',
                'rule':[
                        ['pure'],
                        ['fure'],
                        ['prre'],
                        ['priene'],
                        ['fere'],
                        ['prie'],
                ]
        },
      ]
    },
    {
        'brand':[
                ['neosure'],
                ['nessure'],
              ],
      'text':
      [
        {
        'class':'Similac_NeoSure',
                'rule':[
                        ['neosure'],
                        ['nessure'],
                ]
        },
        {
        'class':'Similac_NeoSure',
                'rule':[
                        ['neosure','premature'],
                        ['neosure','prematurely'],
                ]
        },
      ]
    },
    {
        'brand':[
                ['isomil'],
              ],
      'text':
      [
        {
        'class':'Similac_Isomil_plus',
                'rule':[
                        ['plus','isomil'],
                ]
        },
        {
        'class':'Similac_Soy_Isomil',
                'rule':[
                        ['soy','isomil'],
                ]
        },
      ]
    },
    {
        'brand':[
                ['ensugea'],
                ['ensure'],
                ['ensuirea'],
                ['ensuasaa'],
              ],
      'text':
      [
        
        {
        'class':'Ensure_gold',
                'rule':[
                        ['ensure'],
                        ['ensuasaa'],
                        ['ensugea'],
                        ['ensuirea']
                ]
        },
      ]
    },
    {
        'brand':[
                ['karicare'],
              ],
      'text':
      [
        {
        'class':'karicare_1',
                'rule':[
                        ['1'],
                ]
        },
        {
        'class':'karicare_2',
                'rule':[
                        ['2'],
                ]
        },
        {
        'class':'karicare_3',
                'rule':[
                        ['3'],
                ]
        },
        {
        'class':'karicare_4',
                'rule':[
                        ['4'],
                ]
        },
      ]
    },
    {
        'brand':[
                ['gogrow'],
                ['grgart'],
              ],
      'text':
      [
        
        {
        'class':'Similac_Go_Grow',
                'rule':[
                        ['gogrow'],
                        ['hmo','gogrow'],
                        ['sensitive','gogrow'],
                ]
        },
        {
        'class':'Similac_Go_Grow',
                'rule':[
                        ['grgart'],
                        ['hmo','grgart'],
                        ['sensitive','grgart'],
                ]
        },
        {
        'class':'Similac_Go_Grow',
                'rule':[
                        ['go','grow'],
                        ['hmo','go','grow'],
                        ['gogrow','go','grow'],
                ]
        },
      ]
    },
    {
        'brand':[
                ['similac'],
              ],
      'text':
      [
          {
                'class':'Similac_optigro',
                        'rule':[
                                ['optigro'],
                ]
                  
          },
          {
                'class':'Similac_optigro',
                        'rule':[
                                ['optigro','1'],
                ]
                  
          },
          {
              'class':'Similac_1',
                  'rule':[
                          ['1'],
                          ['infant'],
                          ['formula'],
                  ]
          },
          {
              'class':'Similac_2',
                  'rule':[
                          ['2'],
                  ]
          },
          {
              'class':'Similac_3',
                  'rule':[
                          ['3'],
                          ['8'],
                  ]
          },
          {
              'class':'Similac_4',
                  'rule':[
                          ['4'],
                  ]
          },
          {
              'class':'Similac_Organic',
                  'rule':[
                          ['organic'],
                  ]
          },
          {
              'class':'Similac_Mom',
                  'rule':[
                            ['similac','mom'],

                  ]
          },
          {
              'class':'Similac_360_Total_Care',
                  'rule':[
                          ['360'],
                          ['360','infant'],
                          ['360','sensitive'],
                          ['360','sensitive','infant'],
                          ['total','care'],
                  ]
          },
          {
              'class':'Similac_Pro_Advance',
                  'rule':[
                          ['similac','pro-advance'],
                  ]
          },
          {
              'class':'Similac_Advance',
                  'rule':[
                          ['similac','advance'],
                  ]
          },
          {
              'class':'Similac_Pro_Total_Comfort',
                  'rule':[
                          ['similac','total','comfort'],
                          ['similac','pro-total','comfort'],
                  ]
          },
          {
              'class':'Similac_Pro_Sensitive',
                  'rule':[
                          ['similac','pro-sensitive'],
                  ]
          },
          {
              'class':'Similac_Sensitive',
                  'rule':[
                          ['similac','sensitive'],
                  ]
          },
          {
              'class':'Similac_Alimentum',
                  'rule':[
                          ['similac','alimentum'],
                  ]
          },
          {
              'class':'Similac_For_Spit-Up',
                  'rule':[
                          ['similac','spit','up'],
                          ['similac','spit-up'],
                  ]
          },
          {
              'class':'Similac_MomCare',
                  'rule':[
                          ['momcare'],
                  ]
          }
      ]
    },
    
    {
        'brand':[
                ['pediasure'],
                ['prediasite'],
              ],
      'text':
      [
          {
              'class':'Pediasure_Grow_Gain',
                  'rule':[
                          ['grow','gain'],
                  ]
          },
          {
              'class':'Pediasure',
                  'rule':[
                          ['pediasure'],
                          ['prediasite'],
                  ]
          },
         {
              'class':'Pediasure_10',
                  'rule':[
                          ['10'],
                  ]
          },
      ]
    },
    {
        'brand':[
                ['s-26'],
                ['s-26pe'],
                ['s26pe'],
                ['s26'],
                ['226'],
                ['8-26'],
                ['826'],
                ['s20'],
                ['s-66'],
                ['s-28'],
                ['6-66'],
                ['6-26'],
                ['8-66'],
              ],
      'text':
      [
            {
                'class':'S-26_1',
                    'rule':[
                            ['1'],
                            ['one'],
                            ['infant'],
                    ]
            },
            {
                'class':'S-26_2',
                    'rule':[
                            ['2'],
                            ['follow-up'],
                            ['promil'],
                            ['fromil'],
                            ['follow-up'],
                    ]
            },
            {
                'class':'S-26_2',
                    'rule':[
                            ['promil','gold'],
                    ]
            },
            {
                'class':'S-26_3',
                    'rule':[
                            ['3'],
                            ['13'],
                            ['i3'],
                            ['43'],
                            ['progress'],
                    ]
            },
            {
                'class':'S-26_3',
                    'rule':[
                            ['growing-up','progress'],
                    ]
            },
            {
                'class':'S-26_4',
                    'rule':[
                            ['growing-up','promise'],
                    ]
            },
            {
                'class':'S-26_4',
                    'rule':[
                            ['promise'],
                            ['4'],
                    ]
            },
            {
                'class':'S-26_mama',
                    'rule':[
                            ['mama'],
                            ['matamal'],
                            ['lacteting'],
                    ]
            },
            {
                'class':'S-26_peGold',
                    'rule':[
                            ['pf','gold'],
                    ]
            },
            {
                'class':'S-26_peGold',
                    'rule':[
                            ['pe','gold'],
                    ]
            },
            {
                'class':'S-26_peGold',
                    'rule':[
                                ['s-26pe'],
                                ['s26pe'],
                                ['pegold'],
                    ]
            },
            {
                'class':'ASCENDA',
                    'rule':[
                            ['s26','ascenda'],
                    ]
            },
            {
                'class':'ASCENDA',
                    'rule':[
                            ['learn','ascenda'],
                    ]
            },
            {
                'class':'ASCENDA',
                    'rule':[
                            ['build','ascenda'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['ascenda'],
              ],
      'text':
      [
            {
                'class':'ASCENDA',
                    'rule':[
                            ['ascenda'],
                    ]
            },
            {
                'class':'ASCENDA',
                    'rule':[
                            ['ascenda'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['illuama'],
                ['illuma'],
                ['luma'],
                ['illama'],
              ],
      'text':
      [
            {
                'class':'Illuma_3',
                    'rule':[
                            ['3'],
                    ]
            },
            {
                'class':'Illuma_3',
                    'rule':[
                            ['3','growing-up'],
                            ['3','growing'],
                    ]
            },
            {
                'class':'Illuma_1',
                    'rule':[
                            ['infant'],
                            ['1'],
                    ]
            },
            {
                'class':'Illuma_1',
                    'rule':[
                            ['1','infant'],
                    ]
            },
            {
                'class':'Illuma_2',
                    'rule':[
                            ['2'],
                            ['follow-on'],
                            ['follow'],
                    ]
            },
            {
                'class':'Illuma_2',
                    'rule':[
                            ['2','follow-on'],
                            ['2','follow'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['anmum'],
                ['assura'],
              ],
      'text':
      [
            {
                'class':'Anmum_1',
                    'rule':[
                            ['1'],
                    ]
            },
            {
                'class':'Anmum_2',
                    'rule':[
                            ['2'],
                    ]
            },
            {
                'class':'Anmum_3',
                    'rule':[
                            ['3'],
                            ['8'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['natureone'],
                ['nature'],
                ['dairy'],
                ['au-12'],
                ['activePro'],
              ],
      'text':
      [
            {
                'class':'Natureone_Organic_Newborn_1',
                    'rule':[
                            ['1'],
                            ['newborn'],
                    ]
            },
            {
                'class':'Nature_One_Activegrow',
                    'rule':[
                            ['activegrow'],
                    ]
            },
            {
                'class':'Nature_One_premature',
                    'rule':[
                            ['premature'],
                    ]
            },
            {
                'class':'Nature_One_Newborn_20',
                    'rule':[
                            ['20'],
                    ]
            },
            {
                'class':'Nature_One_Newborn_24',
                    'rule':[
                            ['24'],
                    ]
            },
            {
                'class':'Nature_One_Pregnancy_milk_drink',
                    'rule':[
                            ['pregnancy','milk','drink'],
                    ]
            },
            {
                'class':'Nature_One_Pregnancy',
                    'rule':[
                            ['pregnancy'],
                    ]
            },
            {
                'class':'Natureone_Follow_on_2',
                    'rule':[
                            ['2'],
                            ['follow-on'],
                    ]
            },
            {
                'class':'Natureone_Toddler_3',
                    'rule':[
                            ['3'],
                            ['toddler'],
                    ]
            },
            {
                'class':'Natureone_Toddler_3',
                    'rule':[
                            ['organic','nature','3'],
                    ]
            },
            {
                'class':'Natureone_Junior_4',
                    'rule':[
                            ['4'],
                            ['junior'],
                    ]
            },
            {
                'class':'au_12_1',
                    'rule':[
                            ['au-12','1'],
                    ]
            },
            {
                'class':'au_12_2',
                    'rule':[
                            ['au-12','2'],
                    ]
            },
            {
                'class':'au_12_3',
                    'rule':[
                            ['au-12','3'],
                    ]
            },
            {
                'class':'SureGrow_1',
                    'rule':[
                            ['suregrow','1'],
                    ]
            },
            {
                'class':'SureGrow_2',
                    'rule':[
                            ['suregrow','2'],
                    ]
            },
            {
                'class':'SureGrow_3',
                    'rule':[
                            ['suregrow','3'],
                    ]
            },
            {
                'class':'Dr_Colostrum_1',
                    'rule':[
                            ['dr.colostrum','1'],
                            ['colostrum','1'],
                    ]
            },
            {
                'class':'Dr_Colostrum_2',
                    'rule':[
                            ['dr.colostrum','2'],
                            ['colostrum','2'],
                    ]
            },
            {
                'class':'Dr_Colostrum_3',
                    'rule':[
                            ['dr.colostrum','3'],
                            ['colostrum','3'],
                    ]
            },
            {
                'class':'Nature-One_Pregnancy_formula',
                    'rule':[
                            ['pregnancy'],
                    ]
            },
            {
                'class':'Student',
                    'rule':[
                            ['student'],
                    ]
            },
            {
                'class':'GlucoCare',
                    'rule':[
                            ['glucocare'],
                    ]
            },
            {
                'class':'ActivePro',
                    'rule':[
                            ['activepro'],
                    ]
            },
            {
                'class':'Nature_One_Lactoferrin',
                    'rule':[
                            ['lactoferrin'],
                    ]
            },
            {
                'class':'Nature_One_Full_Cream',
                    'rule':[
                            ['full','cream'],
                    ]
            },
            {
                'class':'Nature_One_Skim',
                    'rule':[
                            ['skim'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['gate'],
                ['cow '],
              ],
      'text':
      [
            {
                'class':'Cow_Gate_1',
                    'rule':[
                            ['gate','cow','1'],
                    ]
            },
            {
                'class':'Cow_Gate_2',
                    'rule':[
                            ['gate','cow','2'],
                    ]
            },
            {
                'class':'Cow_Gate_3',
                    'rule':[
                            ['gate','cow','3'],
                    ]
            },
            {
                'class':'Cow_Gate_4',
                    'rule':[
                            ['gate','cow','4'],
                    ]
            },
            {
                'class':'Cow_Gate_Fruit_Cocktail',
                    'rule':[
                            ['gate','cow','fruit','cocktail'],
                    ]
            },
            {
                'class':'Cow_Gate_Apple_Pear',
                    'rule':[
                            ['gate','cow','apple','pear'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['peak'],
              ],
      'text':
      [
            {
                'class':'Peak',
                    'rule':[
                            ['peak'],
                    ]
            }
      ]
    },
    {
        'brand':[
                ['nutribom'],
              ],
      'text':
      [
            {
                'class':'Nutribom',
                    'rule':[
                            ['nutribom'],
                    ]
            }
      ]
    },
    {
        'brand':[
                ['kendamil'],
              ],
      'text':
      [
            {
                'class':'Kendamil_1',
                    'rule':[
                            ['1'],
                            ['first'],
                    ]
            },
            {
                'class':'Kendamil_2',
                    'rule':[
                            ['2'],
                            ['follow'],
                            ['follow-on'],
                    ]
            },
            {
                'class':'Kendamil_3',
                    'rule':[
                            ['3'],
                            ['toddler'],
                    ]
            },
            {
                'class':'Kendamil_cereal',
                    'rule':[
                            ['4'],
                            ['6'],
                            ['7'],
                            ['10'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['sma'],
                ['sđa'],
                ['sba'],
              ],
      'text':
      [
            {
                'class':'SMA_1',
                    'rule':[
                            ['1'],
                            ['first'],
                            ['from','brirth'],
                    ]
            },
            {
                'class':'SMA_1_pro',
                    'rule':[
                            ['1','pro'],
                            ['first','pro'],
                            ['from','brirth','pro'],
                    ]
            },
            {
                'class':'SMA_1_gold',
                    'rule':[
                            ['1','gold'],
                            ['first','gold'],
                            ['from','brirth','gold'],
                    ]
            },
            {
                'class':'SMA_2_gold',
                    'rule':[
                            ['2','gold'],
                            ['follow-on','gold'],
                            ['affter','6','gold'],
                    ]
            },
            {
                'class':'SMA_2_pro',
                    'rule':[
                            ['2','pro'],
                            ['follow-on','pro'],
                            ['affter','6','pro'],
                    ]
            },
            {
                'class':'SMA_3_gold',
                    'rule':[
                            ['3','gold'],
                            ['toddler','gold'],
                            ['1-3','gold'],
                    ]
            },
            {
                'class':'SMA_3_pro',
                    'rule':[
                            ['3','pro'],
                            ['toddler','pro'],
                            ['1-3','pro'],
                    ]
            },
            {
                'class':'SMA_2',
                    'rule':[
                            ['2'],
                            ['follow-on'],
                            ['affter','6'],
                    ]
            },
            {
                'class':'SMA_3',
                    'rule':[
                            ['3'],
                            ['toddler'],
                            ['1-3'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['fortilac'],
              ],
      'text':
      [
            {
                'class':'Fortilac_1',
                    'rule':[
                            ['1'],
                            ['0-6'],
                            ['infant'],
                    ]
            },
            {
                'class':'Fortilac_2',
                    'rule':[
                            ['2'],
                            ['follow-up'],
                            ['follow','up'],
                            ['6-12'],
                    ]
            },
            {
                'class':'Fortilac_3',
                    'rule':[
                            ['3'],
                            ['growing-up'],
                            ['growing','up'],
                            ['1-3'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['a2'],
                ['platinum'],
              ],
      'text':
      [
            {
                'class':'A2_1',
                    'rule':[
                            ['1'],
                            ['infant'],
                    ]
            },
            {
                'class':'A2_2',
                    'rule':[
                            ['a2','follow-on'],
                            ['a2','follow'],
                    ]
            },
            {
                'class':'A2_2',
                    'rule':[
                            ['2'],
                    ]
            },
            {
                'class':'A2_3',
                    'rule':[
                            ['a2','toddler'],
                            ['a2','toddieg'],
                    ]
            },
            {
                'class':'A2_3',
                    'rule':[
                            ['3'],
                    ]
            },
            {
                'class':'A2_4',
                    'rule':[
                            ['a2','junior'],
                    ]
            },
            {
                'class':'A2_4',
                    'rule':[
                            ['4'],
                    ]
            },
            {
                'class':'A2_4_mothers',
                    'rule':[
                            ['a2','mothers'],
                    ]
            },
            {
                'class':'A2_Full_cream',
                    'rule':[
                            ['full','cream'],
                    ]
            },
            {
                'class':'A2_Smart_Nutrition',
                    'rule':[
                            ['smart','nutrition'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['bellamy'],
              ],
      'text':
      [
            
            {
                'class':'Bellamy_4_cf',
                    'rule':[
                            ['apple','4'],
                    ]
            },
            {
                'class':'Bellamy_4_cf',
                    'rule':[
                            ['baby','4'],
                    ]
            },
            {
                'class':'Bellamy_4_cf',
                    'rule':[
                            ['organic','4','apple'],
                    ]
            },
            {
                'class':'Bellamy_4_Beta',
                    'rule':[
                            ['beta','4'],
                    ]
            },
            {
                'class':'Bellamy_4',
                    'rule':[
                            ['organic','4'],
                    ]
            },
            {
                'class':'Bellamy_3_Beta',
                    'rule':[
                            ['beta','3'],
                    ]
            },
            {
                'class':'Bellamy_2_Beta',
                    'rule':[
                            ['beta','2'],
                    ]
            },
            {
                'class':'Bellamy_1_Beta',
                    'rule':[
                            ['beta','1'],
                    ]
            },
             {
                'class':'Bellamy_3',
                    'rule':[
                            ['toodulr','3'],
                    ]
            },
             {
                'class':'Bellamy_3',
                    'rule':[
                            ['toddler','3'],
                    ]
            },
            {
                'class':'Bellamy_4',
                    'rule':[
                            ['junior','4'],
                    ]
            },
            {
                'class':'Bellamy_4',
                    'rule':[
                            ['jumior','4'],
                    ]
            },
            
            {
                'class':'nnnn',
                    'rule':[
                            ['baby','pregnancy'],
                    ]
            },
            {
                'class':'Bellamy_10',
                    'rule':[
                            ['baby','10'],
                            ['banana','10'],
                    ]
            },
            {
                'class':'Bellamy_8',
                    'rule':[
                            ['baby','8'],
                            ['banana','8'],
                    ]
            },
            {
                'class':'Bellamy_5',
                    'rule':[
                            ['baby','5'],
                            ['banana','5'],
                    ]
            },
            {
                'class':'Bellamy_6',
                    'rule':[
                            ['baby','6'],
                            ['banana','6'],
                    ]
            },
            {
                'class':'Bellamy_7',
                    'rule':[
                            ['baby','7'],
                            ['banana','7'],
                    ]
            },
            {
                'class':'Bellamy_12',
                    'rule':[
                            ['baby','12'],
                            ['banana','12'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ["gentle"],
              ],
      'text':
      [
           {
                'class':'Bellamy_Goat_1',
                    'rule':[
                            ['organic','1'],
                            ['organic','infant'],
                    ]
            },
            {
                'class':'Bellamy_Goat_2',
                    'rule':[
                            ['organic','2'],
                            ['organic','follow'],
                    ]
            },
            {
                'class':'Bellamy_Goat_3',
                    'rule':[
                            ['organic','3'],
                            ['organic','toddler'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['bellamy'],
                ["bellamy's"],
                ["llamy's"],
                ['bellam'],
                ["bellam's"],
                ["blamy's"],
              ],
      'text':
      [
       
            
            {
                'class':'Bellamy_1',
                    'rule':[
                            ['1'],
                            ['infant'],
                    ]
            },
            {
                'class':'Bellamy_2',
                    'rule':[
                            ['2'],
                    ]
            },
            {
                'class':'Bellamy_3',
                    'rule':[
                            ['3'],
                    ]
            },
            {
                'class':'Bellamy_4',
                    'rule':[
                            ['4'],
                    ]
            },
            {
                'class':'Bellamy_Pregnancy',
                    'rule':[
                            ['pregnancy'],
                    ]
            },
            {
                'class':'Bellamy_10',
                    'rule':[
                            ['10'],
                    ]
            },
            {
                'class':'Bellamy_8',
                    'rule':[
                            ['8'],
                            ['&','veggie'],
                    ]
            },
            {
                'class':'Bellamy_5',
                    'rule':[
                            ['5'],
                    ]
            },
            {
                'class':'Bellamy_6',
                    'rule':[
                            ['6'],
                    ]
            },
            {
                'class':'Bellamy_7',
                    'rule':[
                            ['7'],
                    ]
            },
            {
                'class':'Bellamy_12',
                    'rule':[
                            ['12'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['heinz'],
              ],
      'text':
      [
       
            {
                'class':'Heinz_1',
                    'rule':[
                            ['1'],
                    ]
            },
            {
                'class':'Heinz_4',
                    'rule':[
                            ['4'],
                    ]
            },
            {
                'class':'Heinz_6',
                    'rule':[
                            ['6'],
                    ]
            },
            {
                'class':'Heinz_7',
                    'rule':[
                            ['7'],
                    ]
            },
            {
                'class':'Heinz_8',
                    'rule':[
                            ['8'],
                    ]
            },
            {
                'class':'Heinz_10',
                    'rule':[
                            ['10'],
                    ]
            },
      ]
    },
    {
        'brand':[
                ['mamil'],
                ['dumex'],
              ],
      'text':
      [
       
            {
                'class':'Mamil_3',
                    'rule':[
                            ['3'],
                            ['13'],
                    ]
            },
            {
                'class':'Mamil_4',
                    'rule':[
                            ['4'],
                            ['14'],
                    ]
            },
      ]
    }                             
]